name: build/release electron app

on:
  push:
    # sequence of patterns matched against refs/tags
    tags:
      - '*' # push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  app_name: ${{ github.event.repository.name }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build/release Electron app
        uses: hkgnp/action-electron-builder
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
